name: MaSIF
channels:
  - conda-forge
  - bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11
  - ipykernel
  - r-base
  - prody
  - scipy
  - py3dmol
  - emboss
prefix: /home/ymeng/miniconda3/envs/MaSIF
